### ISSUE TITLE
power profile not applying automatically

### ISSUE THREAD

**Issue by GILLEE90** [Valkirie/Thunderbolt-Switch#6]
hello. first of all i love your project! it does a job many people dreamt of.

anyway i found out that the power profile always setted to default. at windwos start, or when i re-open the TS, or i plug and unplug, it always says the TDP setted to 'default'. it works when i manually select from the taskbar (via right click the icon).

i checked 'monitor power profiles' on general settings and my power profiles are as below.

1. docked (trigger is running on current)
2. battery (trigger is running on battery)

thanks and i wait hearing from you :)

**Comment by Valkirie** [comment]
Hey, lovely to hear :)
Please make sure to always tick "When device status changes" and "when application starts" for any power profiles you'd like the software to auto apply on boot and when you plug/unplug it, otherwise you'll have to manually enable them.

![image](https://user-images.githubusercontent.com/934757/123547207-2a36d180-d760-11eb-86e2-99e7b2488b96.png)
![image](https://user-images.githubusercontent.com/934757/123547215-328f0c80-d760-11eb-8a19-c8dd5989c655.png)

**Comment by GILLEE90** [comment]
> Hey, lovely to hear :)
> Please make sure to always tick "When device status changes" and "when application starts" for any power profiles you'd like the software to auto apply on boot and when you plug/unplug it, otherwise you'll have to manually enable them.
> 
> ![image](https://user-images.githubusercontent.com/934757/123547207-2a36d180-d760-11eb-86e2-99e7b2488b96.png)
> ![image](https://user-images.githubusercontent.com/934757/123547215-328f0c80-d760-11eb-8a19-c8dd5989c655.png)

It works now ! thanks :)
